id: I2993297E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T22:21:04+00:00'
last_modified: '2022-06-09T04:34:00.591537+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7889
  title: ཚད་མ་རྣམ་ངེས་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C6D2:
      image_group_id: I3CN7891
      title: Volume 1 of tshad ma rnam nges rtsa 'grel/
      total_pages: 808
      order: 1
      base_file: C6D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
