id: P008109
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7889
  title: ཚད་མ་རྣམ་ངེས་རྩ་འགྲེལ།
  author: ''
  volumes:
    ec2cd632e17a4adb9ce70d1eae28946f:
      image_group_id: I3CN7891
      title: ''
      volume_number: 1
      total_pages: 808
ebook_metadata:
  title: ཚད་མ་རྣམ་ངེས་རྩ་འགྲེལ།
  author: ''
  sku: P008109
  cover: cover.jpg
  layers:
  - pagination
