id: P008109
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:02:15.108170
source_metadata:
  id: bdr:W3CN7889
  title: ཚད་མ་རྣམ་ངེས་རྩ་འགྲེལ།
  author: ''
  volumes:
    905d0bfde34948a6b0403b1313a6689f:
      image_group_id: I3CN7891
      title: Volume 1 of tshad ma rnam nges rtsa 'grel/
      volume_number: 1
      total_pages: 808
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
